# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - flaskCICDtest

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://flaskcicdtest.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_baa6c25881264cb88da7b9b19ae6c0ea }}
        password: ${{ secrets.AzureAppService_ContainerPassword_efce88ec4dca47c3bc01d25bf5fe71d4 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: flaskcicdtest.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_baa6c25881264cb88da7b9b19ae6c0ea }}/mltest:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'flaskCICDtest'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_3006e3e898b5405dbb974db1f7b42a8b }}
        images: 'flaskcicdtest.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_baa6c25881264cb88da7b9b19ae6c0ea }}/mltest:${{ github.sha }}'